apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: {{ .Release.Name }}-frontend-app
